---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: clickhouse
---
apiVersion: v1
kind: Pod
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  containers:
  - name: clickhouse
    image: yandex/clickhouse-server:1.1