/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloWorld_H
#define HelloWorld_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "helloworld_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class HelloWorldIf {
 public:
  virtual ~HelloWorldIf() {}
  virtual void ping() = 0;
  virtual void sayHello(std::string& _return) = 0;
  virtual void sayMsg(std::string& _return, const std::string& msg) = 0;
};

class HelloWorldIfFactory {
 public:
  typedef HelloWorldIf Handler;

  virtual ~HelloWorldIfFactory() {}

  virtual HelloWorldIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloWorldIf* /* handler */) = 0;
};

class HelloWorldIfSingletonFactory : virtual public HelloWorldIfFactory {
 public:
  HelloWorldIfSingletonFactory(const boost::shared_ptr<HelloWorldIf>& iface) : iface_(iface) {}
  virtual ~HelloWorldIfSingletonFactory() {}

  virtual HelloWorldIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(HelloWorldIf* /* handler */) {}

 protected:
  boost::shared_ptr<HelloWorldIf> iface_;
};

class HelloWorldNull : virtual public HelloWorldIf {
 public:
  virtual ~HelloWorldNull() {}
  void ping() {
    return;
  }
  void sayHello(std::string& /* _return */) {
    return;
  }
  void sayMsg(std::string& /* _return */, const std::string& /* msg */) {
    return;
  }
};


class HelloWorld_ping_args {
 public:

  HelloWorld_ping_args(const HelloWorld_ping_args&);
  HelloWorld_ping_args& operator=(const HelloWorld_ping_args&);
  HelloWorld_ping_args() {
  }

  virtual ~HelloWorld_ping_args() throw();

  bool operator == (const HelloWorld_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const HelloWorld_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloWorld_ping_pargs {
 public:


  virtual ~HelloWorld_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloWorld_ping_result {
 public:

  HelloWorld_ping_result(const HelloWorld_ping_result&);
  HelloWorld_ping_result& operator=(const HelloWorld_ping_result&);
  HelloWorld_ping_result() {
  }

  virtual ~HelloWorld_ping_result() throw();

  bool operator == (const HelloWorld_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const HelloWorld_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloWorld_ping_presult {
 public:


  virtual ~HelloWorld_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class HelloWorld_sayHello_args {
 public:

  HelloWorld_sayHello_args(const HelloWorld_sayHello_args&);
  HelloWorld_sayHello_args& operator=(const HelloWorld_sayHello_args&);
  HelloWorld_sayHello_args() {
  }

  virtual ~HelloWorld_sayHello_args() throw();

  bool operator == (const HelloWorld_sayHello_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const HelloWorld_sayHello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_sayHello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloWorld_sayHello_pargs {
 public:


  virtual ~HelloWorld_sayHello_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorld_sayHello_result__isset {
  _HelloWorld_sayHello_result__isset() : success(false) {}
  bool success :1;
} _HelloWorld_sayHello_result__isset;

class HelloWorld_sayHello_result {
 public:

  HelloWorld_sayHello_result(const HelloWorld_sayHello_result&);
  HelloWorld_sayHello_result& operator=(const HelloWorld_sayHello_result&);
  HelloWorld_sayHello_result() : success() {
  }

  virtual ~HelloWorld_sayHello_result() throw();
  std::string success;

  _HelloWorld_sayHello_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const HelloWorld_sayHello_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloWorld_sayHello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_sayHello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorld_sayHello_presult__isset {
  _HelloWorld_sayHello_presult__isset() : success(false) {}
  bool success :1;
} _HelloWorld_sayHello_presult__isset;

class HelloWorld_sayHello_presult {
 public:


  virtual ~HelloWorld_sayHello_presult() throw();
  std::string* success;

  _HelloWorld_sayHello_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _HelloWorld_sayMsg_args__isset {
  _HelloWorld_sayMsg_args__isset() : msg(false) {}
  bool msg :1;
} _HelloWorld_sayMsg_args__isset;

class HelloWorld_sayMsg_args {
 public:

  HelloWorld_sayMsg_args(const HelloWorld_sayMsg_args&);
  HelloWorld_sayMsg_args& operator=(const HelloWorld_sayMsg_args&);
  HelloWorld_sayMsg_args() : msg() {
  }

  virtual ~HelloWorld_sayMsg_args() throw();
  std::string msg;

  _HelloWorld_sayMsg_args__isset __isset;

  void __set_msg(const std::string& val);

  bool operator == (const HelloWorld_sayMsg_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const HelloWorld_sayMsg_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_sayMsg_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloWorld_sayMsg_pargs {
 public:


  virtual ~HelloWorld_sayMsg_pargs() throw();
  const std::string* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorld_sayMsg_result__isset {
  _HelloWorld_sayMsg_result__isset() : success(false) {}
  bool success :1;
} _HelloWorld_sayMsg_result__isset;

class HelloWorld_sayMsg_result {
 public:

  HelloWorld_sayMsg_result(const HelloWorld_sayMsg_result&);
  HelloWorld_sayMsg_result& operator=(const HelloWorld_sayMsg_result&);
  HelloWorld_sayMsg_result() : success() {
  }

  virtual ~HelloWorld_sayMsg_result() throw();
  std::string success;

  _HelloWorld_sayMsg_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const HelloWorld_sayMsg_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloWorld_sayMsg_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_sayMsg_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorld_sayMsg_presult__isset {
  _HelloWorld_sayMsg_presult__isset() : success(false) {}
  bool success :1;
} _HelloWorld_sayMsg_presult__isset;

class HelloWorld_sayMsg_presult {
 public:


  virtual ~HelloWorld_sayMsg_presult() throw();
  std::string* success;

  _HelloWorld_sayMsg_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloWorldClient : virtual public HelloWorldIf {
 public:
  HelloWorldClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloWorldClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void sayHello(std::string& _return);
  void send_sayHello();
  void recv_sayHello(std::string& _return);
  void sayMsg(std::string& _return, const std::string& msg);
  void send_sayMsg(const std::string& msg);
  void recv_sayMsg(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloWorldProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<HelloWorldIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (HelloWorldProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_sayHello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_sayMsg(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloWorldProcessor(boost::shared_ptr<HelloWorldIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &HelloWorldProcessor::process_ping;
    processMap_["sayHello"] = &HelloWorldProcessor::process_sayHello;
    processMap_["sayMsg"] = &HelloWorldProcessor::process_sayMsg;
  }

  virtual ~HelloWorldProcessor() {}
};

class HelloWorldProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloWorldProcessorFactory(const ::boost::shared_ptr< HelloWorldIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< HelloWorldIfFactory > handlerFactory_;
};

class HelloWorldMultiface : virtual public HelloWorldIf {
 public:
  HelloWorldMultiface(std::vector<boost::shared_ptr<HelloWorldIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloWorldMultiface() {}
 protected:
  std::vector<boost::shared_ptr<HelloWorldIf> > ifaces_;
  HelloWorldMultiface() {}
  void add(boost::shared_ptr<HelloWorldIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void sayHello(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sayHello(_return);
    }
    ifaces_[i]->sayHello(_return);
    return;
  }

  void sayMsg(std::string& _return, const std::string& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sayMsg(_return, msg);
    }
    ifaces_[i]->sayMsg(_return, msg);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class HelloWorldConcurrentClient : virtual public HelloWorldIf {
 public:
  HelloWorldConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloWorldConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void sayHello(std::string& _return);
  int32_t send_sayHello();
  void recv_sayHello(std::string& _return, const int32_t seqid);
  void sayMsg(std::string& _return, const std::string& msg);
  int32_t send_sayMsg(const std::string& msg);
  void recv_sayMsg(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
