/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "helloworld_constants.h"



const helloworldConstants g_helloworld_constants;

helloworldConstants::helloworldConstants() {
  HELLO_IN_KOREAN = "an-nyoung-ha-se-yo";

  HELLO_IN_FRENCH = "bonjour!";

  HELLO_IN_JAPANESE = "konichiwa!";

}



